name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: davidgraeff/rust-musl-action@master
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release
