name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: clux/muslrust:stable
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        HOME=/root cargo +stable build --target x86_64-unknown-linux-musl --release
        find .
        mv target/release/gts-port-cfg $GITHUB_WORKSPACE
    - name: Upload statically linked binary
      uses: actions/upload-artifact@v1
      with:
        name: gts-port-cfg
        path: $GITHUB_WORKSPACE/gts-port-cfg
