name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: clux/muslrust:stable
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        rustup toolchain list
        cargo build --target x86_64-unknown-linux-musl --release
    - name: Upload statically linked binary
      uses: actions/upload-artifact@v1
      with:
        name: gts-port-cfg
        path: target/release/gts-port-cfg
